repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: mixed-line-ending
        args:
            - --fix=lf
    -   id: check-added-large-files
        args:
            - --maxkb=2048
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: destroyed-symlinks
    -   id: fix-byte-order-marker
    -   id: check-yaml
        args:
            - --allow-multiple-documents
            - --unsafe
    -   id: trailing-whitespace
        args:
            - --markdown-linebreak-ext=md
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0  # or specific git tag
  hooks:
    - id: markdownlint # Configure in .mdlrc
      args:
          - --git-recurse
          - --ignore-front-matter
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      files: \.py$
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.9.0
  hooks:
    - id: black
      files: \.py$
      args:
          - --line-length=90
          - --target-version=py313
          - -x
      language_version: python3.13
